name: CI/CD with Trivy and Tests

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run Unit Tests
        run: |
          go mod tidy
          go test -v ./...

  build-and-scan:
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t samuel05x/microservicio-user:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: samuel05x/microservicio-user:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker image
        run: |
          docker push samuel05x/microservicio-user:latest

  integration-tests:
    needs: build-and-scan
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull samuel05x/microservicio-user:latest

      - name: Run image and validate container execution
        run: |
          docker run --rm samuel05x/microservicio-user:latest || exit 1
