name: Release Build & Publish

on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LC=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image with version tag
        run: |
          docker build -t samuel05x/microservicio-user:${{ github.event.release.tag_name }} \
                       -t ghcr.io/${REPO_OWNER_LC}/microservicio-user:${{ github.event.release.tag_name }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: samuel05x/microservicio-user:${{ github.event.release.tag_name }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker image to DockerHub and GHCR
        run: |
          docker push samuel05x/microservicio-user:${{ github.event.release.tag_name }}
          docker push ghcr.io/${REPO_OWNER_LC}/microservicio-user:${{ github.event.release.tag_name }}
